AllCops:
  TargetRubyVersion: 2.3
Metrics/AbcSize:
  Max: 35
StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
